10 REM ===== EDIT COMMAND TEST =====
20 PRINT "EDIT Command Test"
30 PRINT "================="
40 PRINT ""
50 PRINT "EDIT brings up a line for immediate editing"
60 PRINT "Arrow keys work for cursor movement"
70 PRINT "Backspace deletes characters"
80 PRINT ""
90 REM Create some lines to edit
100 PRINT "Creating test lines..."
110 LET line1="10 PRINT \"Hello\""
120 LET line2="20 PRINT \"World\""
130 PRINT ""
140 PRINT "Test lines created:"
150 PRINT "  10 PRINT \"Hello\""
160 PRINT "  20 PRINT \"World\""
170 PRINT ""
180 INPUT "Press Enter to test EDIT: "; x
190 PRINT ""
200 PRINT "Type: EDIT 10"
210 PRINT "Then modify the line and press Enter"
220 PRINT "Cursor should be ready at end of content"
230 PRINT ""
240 PRINT "Tips:"
250 PRINT "  - Arrow keys move cursor left/right"
260 PRINT "  - Backspace deletes character before cursor"
270 PRINT "  - Type to insert characters"
280 PRINT "  - Enter saves the line"
290 PRINT "  - Ctrl+C cancels edit"
300 PRINT ""
310 PRINT "EDIT command test complete"
320 END
